import { Alert, Platform, type AlertButton } from 'react-native';

const EN: Record<string, string> = {
  '正在加载…': 'Loading…',
  '发现新版本': 'New version available',
  '已下载更新，重启应用即可生效。': 'The update is downloaded. Restart the app to apply it.',
  '立即重启': 'Restart now',
  '任务': 'Tasks',
  '项目': 'Projects',
  '我的': 'Profile',
  '跟随系统': 'System default',
  '浅色': 'Light',
  '深色': 'Dark',
  '官方网站': 'Official website',
  '帮助文档': 'Documentation',
  'GitHub 开源仓库': 'GitHub repository',
  '更新失败': 'Update failed',
  '下载失败，请检查网络后重试。': 'Download failed. Check your network and try again.',
  '新版本 v': 'New version v',
  '可用，需前往下载安装新版本。': ' is available. Go to download and install it.',
  '去更新': 'Update',
  '检查更新': 'Check for updates',
  '开发模式下不可用，正式包才会检查更新。': 'Unavailable in development mode. Updates are checked in release builds.',
  '已是最新': 'Up to date',
  '当前已是最新版本 ': 'You are using the latest version ',
  '有新版本可用，是否立即更新？': 'A new version is available. Update now?',
  '（更新后将自动重启）': '(The app will restart automatically after updating.)',
  '正在检查…': 'Checking…',
  '正在下载更新…': 'Downloading update…',
  '当前版本 ': 'Current version ',
  '旗舰会员': 'Premium',
  '专业会员': 'Pro',
  '基础会员': 'Basic',
  '无额度': 'No quota',
  '剩余 ': 'Remaining ',
  '签到中': 'Checking in',
  '签到 +': 'Check in +',
  '邮箱格式不正确': 'Invalid email address',
  '请输入有效的邮箱地址。': 'Enter a valid email address.',
  '验证邮件已发送': 'Verification email sent',
  '请前往 ': 'Go to ',
  ' 查收验证邮件，完成验证后邮箱会显示在本页。': ' to check your verification email. Your email will appear here after verification.',
  '绑定邮箱失败': 'Failed to link email',
  '签到成功，+': 'Check-in successful, +',
  ' 积分': ' points',
  '签到失败，请重试': 'Check-in failed. Try again.',
  '退出登录': 'Sign out',
  '确定要退出当前账号吗？': 'Are you sure you want to sign out?',
  '退出': 'Sign out',
  '注销账号': 'Delete account',
  '注销后，你的账号及全部数据将被永久删除，无法恢复；Apple 登录的授权也会一并撤销。': 'Deleting your account permanently removes your account and all data and cannot be undone. Apple authorization will also be revoked.',
  '继续': 'Continue',
  '确认永久删除？': 'Permanently delete account?',
  '此操作不可撤销。': 'This action cannot be undone.',
  '永久删除': 'Delete permanently',
  '注销失败': 'Account deletion failed',
  '请稍后重试。如多次失败，请通过官网联系我们处理。': 'Please try again later. If it keeps failing, contact us through the official website.',
  '用户': 'User',
  '未绑定邮箱': 'No email linked',
  '用户 ID 已复制': 'User ID copied',
  '邀请链接已复制，分享给好友': 'Invite link copied. Share it with a friend.',
  '有效期至 ': 'Valid until ',
  '长期有效': 'No expiration',
  '免费模型': 'Free model',
  'Git 账号': 'Git account',
  '绑定代码仓库凭证': 'Link repository credentials',
  '自定义模型': 'Custom models',
  '接入自己的大模型': 'Connect your own AI model',
  '积分余额': 'Points balance',
  '已邀请 ': 'Invited ',
  ' 人': ' people',
  '每邀请一位 +': 'Each invite earns +',
  ' 积分': ' points',
  '邀请好友': 'Invite friends',
  '今日已签到': 'Checked in today',
  '加载失败': 'Failed to load',
  '加载项目…': 'Loading projects…',
  '共 ': 'Total ',
  ' 个项目': ' projects',
  '暂无项目': 'No projects yet',
  '绑定 Git 身份并关联仓库后，即可创建项目': 'Link a Git identity and repository to create a project',
  '新建项目': 'New project',
  '没有更多了': 'No more items',
  '进行中': 'In progress',
  '已结束': 'Finished',
  '终止任务': 'Stop task',
  '确定终止「': 'Stop “',
  '」？': '”?',
  '终止失败': 'Failed to stop task',
  '删除任务': 'Delete task',
  '删除「': 'Delete “',
  '」？此操作不可恢复。': '”? This action cannot be undone.',
  '删除失败': 'Delete failed',
  '智能任务': 'AI tasks',
  '加载任务…': 'Loading tasks…',
  '没有进行中的任务': 'No tasks in progress',
  '还没有已结束的任务': 'No finished tasks yet',
  '点右下角 + 发起一个 AI 任务': 'Tap + in the bottom-right to start an AI task',
  '加载失败，请重试': 'Failed to load. Try again.',
  '移除账号': 'Remove account',
  '确定要移除「': 'Remove “',
  '」吗？使用该账号的项目将无法继续拉取/提交代码。': '”? Projects using this account will no longer be able to pull or push code.',
  '移除': 'Remove',
  '无法移除': 'Unable to remove',
  '一键授权': 'Authorize',
  '其他平台': 'Other platforms',
  '手动填写 Access Token': 'Enter Access Token manually',
  '加载账号中…': 'Loading accounts…',
  '还没有 Git 账号': 'No Git accounts yet',
  '绑定 GitHub / GitLab / Gitee 等账号后\\n即可创建项目，让 AI 拉取与提交代码': 'Link a GitHub, GitLab, Gitee, or other account\\nto create projects and let AI pull and push code',
  '刷新失败：': 'Refresh failed: ',
  '添加 Git 账号': 'Add Git account',
  '账号不存在': 'Account not found',
  '该 Git 账号可能已被移除。': 'This Git account may have been removed.',
  '请选择 Git 平台类型': 'Select a Git platform',
  '请输入 Git 平台地址': 'Enter the Git platform URL',
  '请输入 Access Token': 'Enter Access Token',
  '请输入用户名': 'Enter a username',
  '用户名不能包含括号、引号等特殊字符': 'Username cannot contain brackets, quotes, or other special characters',
  '请输入邮箱地址': 'Enter an email address',
  '保存失败': 'Save failed',
  '绑定失败': 'Linking failed',
  '加载账号…': 'Loading account…',
  '编辑 Git 账号': 'Edit Git account',
  'Git 平台类型': 'Git platform',
  '请选择平台': 'Select a platform',
  'Git 平台地址': 'Git platform URL',
  '（留空不修改）': ' (leave blank to keep unchanged)',
  '如何获取': 'How to get it',
  '用户名': 'Username',
  'Git 平台用户名': 'Git platform username',
  '提交代码用的邮箱地址': 'Email address used for commits',
  '邮箱': 'Email',
  '备注（选填）': 'Note (optional)',
  '便于区分多个账号，如「我的 GitHub」': 'Helps distinguish multiple accounts, e.g. “My GitHub”',
  '选择 Git 平台': 'Select Git platform',
  '重试': 'Retry',
  '链接已复制': 'Link copied',
  '绑定 ': 'Link ',
  '正在准备授权…': 'Preparing authorization…',
  '正在完成绑定': 'Finishing account link',
  '请先阅读并同意《用户协议》和《隐私政策》': 'Please read and agree to the User Agreement and Privacy Policy.',
  '正在完成登录…': 'Finishing sign-in…',
  '登录失败，请重试': 'Sign-in failed. Try again.',
  '正在完成 GitHub 登录…': 'Finishing GitHub sign-in…',
  'GitHub 登录': 'GitHub sign-in',
  'GitHub 登录失败，请重试': 'GitHub sign-in failed. Try again.',
  '正在登录…': 'Signing in…',
  '未获取到 Apple 登录凭证': 'Apple sign-in credential was not received',
  '当前服务器未开启 Apple 登录': 'Apple sign-in is not enabled on this server',
  'Apple 登录失败，请重试': 'Apple sign-in failed. Try again.',
  '正在打开抖音…': 'Opening Douyin…',
  '正在完成抖音登录…': 'Finishing Douyin sign-in…',
  '抖音登录': 'Douyin sign-in',
  '抖音登录失败，请重试': 'Douyin sign-in failed. Try again.',
  '正在打开 GitHub…': 'Opening GitHub…',
  '打开 GitHub 登录失败，请重试': 'Failed to open GitHub sign-in. Try again.',
  '支付宝登录': 'Alipay sign-in',
  '正在打开支付宝…': 'Opening Alipay…',
  '正在完成支付宝登录…': 'Finishing Alipay sign-in…',
  '打开支付宝登录失败，请重试': 'Failed to open Alipay sign-in. Try again.',
  '正在恢复支付宝登录…': 'Restoring Alipay sign-in…',
  '支付宝登录失败，请重试': 'Alipay sign-in failed. Try again.',
  '请输入邮箱和密码': 'Enter your email and password',
  '请输入有效的手机号': 'Enter a valid phone number',
  '验证码发送失败，请稍后重试': 'Failed to send verification code. Try again later.',
  '请输入短信验证码': 'Enter the SMS verification code',
  '手机号登录': 'Phone sign-in',
  '正在确认授权…': 'Confirming authorization…',
  '授权登录': 'Authorized sign-in',
  '请输入手机号': 'Enter your phone number',
  '短信验证码': 'SMS verification code',
  '获取验证码': 'Get code',
  '登录中…': 'Signing in…',
  '请输入密码': 'Enter password',
  '用户名:密码': 'Username:password',
  '智能开发平台': 'AI development platform',
  '欢迎回来 👋': 'Welcome back 👋',
  '登录以继续你的智能开发之旅': 'Sign in to continue your AI development journey',
  '账号密码登录': 'Email & password sign-in',
  '其它登录方式': 'Other sign-in options',
  '我已阅读并同意': 'I have read and agree to ',
  '和': ' and ',
  '服务器地址': 'Server URL',
  '私有化 / 离线部署可在此填写你的服务地址。': 'Enter your private or offline deployment server URL here.',
  'Basic Auth（可选）': 'Basic Auth (optional)',
  '测试环境若有 HTTP Basic Auth 代理鉴权，在此填写「用户名:密码」，会作为 Authorization 头发送。': 'For test environments using HTTP Basic Auth, enter “username:password” here. It will be sent as an Authorization header.',
  '未设置模型 API 地址': 'Model API URL is not set',
  '模型地址不合法': 'Invalid model URL',
  '实际请求 ': 'Actual request: ',
  '检查模型中…': 'Checking model…',
  '保存中…': 'Saving…',
  '模型不存在': 'Model not found',
  '该模型可能已被删除。': 'This model may have been deleted.',
  '请先输入 API Token': 'Enter an API Token first',
  '未获取到可用模型': 'No available models found',
  '可直接在「模型名称」中手动填写（与服务商 API 一致）。': 'You can enter the model name manually (it must match the provider API).',
  '获取模型列表失败': 'Failed to fetch model list',
  '网络错误': 'Network error',
  '可直接手动填写模型名称。': 'You can enter the model name manually.',
  '请输入模型 API 地址': 'Enter the model API URL',
  '请输入 API Token': 'Enter API Token',
  '请填写或选择模型名称': 'Enter or select a model name',
  '上下文长度必须为大于 0 的整数': 'Context length must be an integer greater than 0',
  '输出长度必须为大于 0 的整数': 'Output length must be an integer greater than 0',
  '模型配置检查失败': 'Model configuration check failed',
  '请确认 API 地址、Token 与模型名称无误。': 'Check the API URL, token, and model name.',
  '模型检查失败': 'Model check failed',
  '修改模型失败': 'Failed to edit model',
  '绑定模型失败': 'Failed to link model',
  '加载模型配置…': 'Loading model configuration…',
  '编辑模型': 'Edit model',
  '接口格式': 'API format',
  '模型 API 地址': 'Model API URL',
  '模型名称': 'Model name',
  '与服务商 API 一致，如 deepseek-chat': 'Must match the provider API, e.g. deepseek-chat',
  '拉取列表': 'Fetch list',
  '模型展示名，如「我的 DeepSeek」': 'Display name, e.g. “My DeepSeek”',
  '高级配置': 'Advanced settings',
  '上下文长度': 'Context length',
  '输出长度': 'Output length',
  '推理 / 思考': 'Reasoning / thinking',
  '模型支持思考模式时开启': 'Enable when the model supports reasoning',
  '图片识别': 'Image input',
  '开启后该模型可接收图片输入': 'Allows this model to receive image inputs',
  '添加模型': 'Add model',
  '检查并保存': 'Check & save',
  '选择模型': 'Select model',
  '删除模型': 'Delete model',
  '确定要删除「': 'Delete “',
  '」吗？删除后使用该模型的任务需改用其它模型。': '”? Tasks using this model will need another model.',
  '删除文件': 'Delete file',
  '读取文件': 'Read file',
  '执行命令': 'Run command',
  '查找内容': 'Search content',
  '获取网页': 'Fetch webpage',
  '移动文件': 'Move file',
  '思考': 'Think',
  '修改文件失败': 'Edit file failed',
  '正在修改文件': 'Editing file',
  '修改文件': 'Edit file',
  '工具调用': 'Tool call',
  '（命令输出为空）': '(command output is empty)',
  '已回答': 'Answered',
  '问题已过期': 'Question expired',
  '请输入回答': 'Enter an answer',
  'AI 提问': 'AI question',
  '其他': 'Other',
  '提交回答': 'Submit answer',
  '收起': 'Collapse',
  '展开完整错误': 'Show full error',
  '文件': 'Files',
  '变动': 'Changes',
  '代码文件': 'Code files',
  '根目录': 'Root',
  '此目录为空': 'This folder is empty',
  '暂无文件改动': 'No file changes',
  '正在下载 ': 'Downloading ',
  '已下载 ': 'Downloaded ',
  '正在准备…': 'Preparing…',
  '正在上传 ': 'Uploading ',
  '上传成功': 'Upload successful',
  '上传失败': 'Upload failed',
  '无法下载': 'Unable to download',
  '无法上传': 'Unable to upload',
  '开发环境不可用，请稍后重试': 'Development environment unavailable. Try again later.',
  '覆盖同名文件？': 'Overwrite existing file?',
  '当前目录已存在“': 'The current folder already contains “',
  '”，继续上传会覆盖它。': '”. Continue to upload and overwrite it?',
  '覆盖': 'Overwrite',
  '已下载': 'Downloaded',
  '已保存': 'Saved',
  '文件已保存到所选位置': 'File saved to the selected location',
  '文件已保存到所选文件夹': 'File saved to the selected folder',
  '该目录不可写': 'This folder is not writable',
  '下载完成': 'Download complete',
  '保存到设备': 'Save to device',
  '分享': 'Share',
  '网络错误': 'Network error',
  '下载内容为空': 'Downloaded content is empty',
  '保存图片': 'Save image',
  '保存这张图片？': 'Save this image?',
  '已保存到相册': 'Saved to photo library',
  '无法打开相册': 'Unable to open photo library',
  '已复制': 'Copied',
  '任务 ID 已复制': 'Task ID copied',
  '切换模型': 'Switch model',
  '选择': 'Select',
  '展开': 'Expand',
  '访问': 'Open',
  '在线预览': 'Live preview',
  '端口 ': 'Port ',
  '更多': 'More',
  'AI 正在处理': 'AI is processing',
  '正在连接语音服务': 'Connecting to voice service',
  '正在转写': 'Transcribing',
  '正在录音，点击结束': 'Recording, tap to stop',
  '任务正在启动，请稍候': 'Task is starting. Please wait',
  '任务已结束，无法继续对话': 'Task has ended. You cannot continue the conversation.',
  '暂无对话': 'No conversation yet',
  '该任务没有可展示的对话记录': 'This task has no conversation history to display',
  '正在初始化': 'Initializing',
  '正在拉取系统镜像': 'Pulling system image',
  '正在克隆代码仓库': 'Cloning repository',
  '正在构建系统镜像': 'Building system image',
  '正在创建开发环境': 'Creating development environment',
  '正在启动开发环境': 'Starting development environment',
  '开发环境已准备好': 'Development environment is ready',
  '无法创建开发环境': 'Unable to create development environment',
  '正在准备云开发环境，启动完成后即可开始对话': 'Preparing the cloud development environment. You can start chatting when it is ready.',
  '加载项目': 'Loading project',
  '还没有任务': 'No tasks yet',
  '点下方按钮在此仓库发起一个': 'Tap the button below to start one in this repository',
  '在此仓库发起任务': 'Start task in this repository',
  '使用技能': 'Use skill',
  '压缩对话': 'Compact conversation',
  '压缩上下文，释放 token 空间': 'Compact context to free token space',
  '重启 Agent': 'Restart Agent',
  '重启 Agent 并保留当前上下文': 'Restart the Agent and keep the current context',
  '重置对话': 'Reset conversation',
  '清空上下文并重启 Agent': 'Clear the context and restart the Agent',
  '无法选择 zip 文件': 'Unable to select a zip file',
  '请描述你想让 AI 做什么': 'Describe what you want the AI to do',
  '请选择 zip 文件': 'Select a zip file',
  '任务创建成功但未返回 ID': 'Task created but no ID was returned',
  '任务创建失败，请重试': 'Failed to create task. Try again.',
  '新建任务': 'New task',
  '你想让我做什么呢？': 'What would you like me to do?',
  '代码仓库': 'Repository',
  '选择模型': 'Select model',
  '描述任务，比如：修复登录页 token 刷新失效的问题，并补充测试…': 'Describe the task, e.g. fix the login token refresh issue and add tests…',
  '试试这些': 'Try these',
  '发起任务': 'Start task',
  '正在上传…': 'Uploading…',
  '正在创建…': 'Creating…',
  '快速开始': 'Quick start',
  '不关联仓库': 'No repository',
  '上传 Zip 文件': 'Upload ZIP file',
  '选择本地 .zip 压缩包': 'Select a local .zip archive',
  '手动输入仓库地址': 'Enter repository URL manually',
  '填写 Git 仓库地址': 'Enter a Git repository URL',
  '选择仓库': 'Select repository',
  '搜索仓库名称': 'Search repository name',
  '列表里没有？直接填写 Git 仓库地址': 'Not listed? Enter the Git repository URL directly',
  '该账号暂无可访问的仓库': 'This account has no accessible repositories',
  '没有匹配的仓库': 'No matching repositories',
  '请填写项目名称': 'Enter a project name',
  '请填写项目名称': 'Enter a project name',
  '关联一个代码仓库': 'Link a repository',
  '给项目起个名字': 'Name your project',
  '请先选择 Git 账号': 'Select a Git account first',
  '选择已绑定的账号': 'Select a linked account',
  '管理 Git 账号': 'Manage Git accounts',
  '没有合适的账号？': 'Need a different account?',
  '正在创建…': 'Creating…',
  '创建项目': 'Create project',
  '选择 Git 账号': 'Select Git account',
  '还没有自定义模型': 'No custom models yet',
  '绑定你自己的大模型 API\\n即可在发起任务时选用': 'Link your own AI model API\\nto use it when starting a task',
  '检查': 'Check',
  '保存': 'Save',
  '未获取到授权地址，请重试': 'Authorization URL was not received. Try again.',
  '百智云网络请求失败': 'BaiZhiCloud network request failed',
  '百智云请求失败（': 'BaiZhiCloud request failed (',
  '百智云验证码': 'BaiZhiCloud verification code',
  '响应格式异常': 'Invalid response format',
  '百智云验证码校验失败': 'BaiZhiCloud verification failed',
  '支付宝授权参数响应格式异常': 'Invalid Alipay authorization response',
  '任务出错': 'Task error',
  '已请求取消当前执行': 'Cancel request sent',
  '启动上下文压缩': 'Starting context compaction',
  '上下文压缩完成': 'Context compaction complete',
  '模型调用失败，正在重试': 'Model request failed, retrying',
  '当前没有可用技能指令': 'No skill commands are currently available',
  '重启并清空上下文': 'Restart and clear context',
  '将清空当前对话上下文并重启 Agent，确定继续？': 'This will clear the current conversation context and restart the Agent. Continue?',
  '清空并重启': 'Clear and restart',
  '加载模型中…': 'Loading models…',
  '我的模型': 'My models',
  '添加模型': 'Add model',
  '耗时 ': 'Elapsed ',
  ' 秒': ' s',
};

const ENTRIES = Object.entries(EN).sort((a, b) => b[0].length - a[0].length);

export function uiText(value: string | null | undefined): string | null | undefined {
  if (value == null || Platform.OS !== 'android') return value;
  let out = value;
  for (const [zh, en] of ENTRIES) out = out.split(zh).join(en);
  return out;
}

export function uiButtons(buttons?: AlertButton[]): AlertButton[] | undefined {
  if (!buttons || Platform.OS !== 'android') return buttons;
  return buttons.map((b) => ({ ...b, text: b.text ? uiText(b.text)! : b.text }));
}

export function androidAlert(
  title: string,
  message?: string,
  buttons?: AlertButton[],
  options?: Parameters<typeof Alert.alert>[3],
) {
  Alert.alert(uiText(title) ?? title, uiText(message) ?? message, uiButtons(buttons), options);
}
